//! Radical data, recipe system, and forge logic.

/// A Chinese radical with its unicode representation and meaning.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Radical {
    pub ch: &'static str,
    pub name: &'static str,
    pub meaning: &'static str,
}

/// A recipe: combining radicals produces a character with an effect.
#[derive(Clone, Copy, Debug)]
pub struct Recipe {
    pub inputs: &'static [&'static str], // radical chars
    pub output_hanzi: &'static str,
    pub output_pinyin: &'static str,
    pub output_meaning: &'static str,
    pub effect: SpellEffect,
}

/// What a forged character does when used as a spell in combat.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SpellEffect {
    /// Deal damage to all visible enemies
    FireAoe(i32),
    /// Heal the player
    Heal(i32),
    /// Block the next incoming hit
    Shield,
    /// Deal extra damage to current target
    StrongHit(i32),
}

impl SpellEffect {
    pub fn label(&self) -> &'static str {
        match self {
            SpellEffect::FireAoe(_) => "🔥 Fire",
            SpellEffect::Heal(_) => "💚 Heal",
            SpellEffect::Shield => "🛡 Shield",
            SpellEffect::StrongHit(_) => "⚔ Strike",
        }
    }
}

/// A forged spell the player can use in combat.
#[derive(Clone, Debug)]
pub struct Spell {
    pub hanzi: &'static str,
    pub pinyin: &'static str,
    pub meaning: &'static str,
    pub effect: SpellEffect,
}

// ── Radical catalog ─────────────────────────────────────────────────────────

pub const RADICALS: &[Radical] = &[
    Radical { ch: "火", name: "huǒ", meaning: "fire" },
    Radical { ch: "水", name: "shuǐ", meaning: "water" },
    Radical { ch: "木", name: "mù", meaning: "wood" },
    Radical { ch: "金", name: "jīn", meaning: "metal/gold" },
    Radical { ch: "土", name: "tǔ", meaning: "earth" },
    Radical { ch: "日", name: "rì", meaning: "sun/day" },
    Radical { ch: "月", name: "yuè", meaning: "moon/month" },
    Radical { ch: "心", name: "xīn", meaning: "heart" },
    Radical { ch: "口", name: "kǒu", meaning: "mouth" },
    Radical { ch: "手", name: "shǒu", meaning: "hand" },
    Radical { ch: "目", name: "mù", meaning: "eye" },
    Radical { ch: "人", name: "rén", meaning: "person" },
    Radical { ch: "大", name: "dà", meaning: "big" },
    Radical { ch: "小", name: "xiǎo", meaning: "small" },
    Radical { ch: "山", name: "shān", meaning: "mountain" },
    Radical { ch: "石", name: "shí", meaning: "stone" },
    Radical { ch: "雨", name: "yǔ", meaning: "rain" },
    Radical { ch: "风", name: "fēng", meaning: "wind" },
    Radical { ch: "刀", name: "dāo", meaning: "knife" },
    Radical { ch: "力", name: "lì", meaning: "power" },
    Radical { ch: "田", name: "tián", meaning: "field" },
    Radical { ch: "女", name: "nǚ", meaning: "woman" },
    Radical { ch: "子", name: "zǐ", meaning: "child" },
    Radical { ch: "王", name: "wáng", meaning: "king" },
    Radical { ch: "竹", name: "zhú", meaning: "bamboo" },
    Radical { ch: "米", name: "mǐ", meaning: "rice" },
    Radical { ch: "虫", name: "chóng", meaning: "insect" },
    Radical { ch: "贝", name: "bèi", meaning: "shell/treasure" },
    Radical { ch: "马", name: "mǎ", meaning: "horse" },
    Radical { ch: "鸟", name: "niǎo", meaning: "bird" },
];

// ── Recipes (verified via hanzicraft.com decomposition) ─────────────────────
// All recipes verified: inputs match actual Level 1 components (recursively
// decomposed to game radicals). Generated by tools/verify_recipes.py.

pub const RECIPES: &[Recipe] = &[
    // Fire / AoE combos
    Recipe { inputs: &["日", "月"], output_hanzi: "明", output_pinyin: "míng", output_meaning: "bright/clear", effect: SpellEffect::FireAoe(3) },
    Recipe { inputs: &["雨", "田"], output_hanzi: "雷", output_pinyin: "léi", output_meaning: "thunder", effect: SpellEffect::FireAoe(5) },
    Recipe { inputs: &["火", "虫"], output_hanzi: "烛", output_pinyin: "zhú", output_meaning: "candle/flame", effect: SpellEffect::FireAoe(3) },
    Recipe { inputs: &["口", "鸟"], output_hanzi: "鸣", output_pinyin: "míng", output_meaning: "cry of a bird", effect: SpellEffect::FireAoe(2) },
    // Healing combos
    Recipe { inputs: &["女", "子"], output_hanzi: "好", output_pinyin: "hǎo", output_meaning: "good/well", effect: SpellEffect::Heal(6) },
    Recipe { inputs: &["木", "口"], output_hanzi: "杏", output_pinyin: "xìng", output_meaning: "apricot", effect: SpellEffect::Heal(3) },
    Recipe { inputs: &["木", "子"], output_hanzi: "李", output_pinyin: "lǐ", output_meaning: "plum tree", effect: SpellEffect::Heal(2) },
    Recipe { inputs: &["木", "目", "心"], output_hanzi: "想", output_pinyin: "xiǎng", output_meaning: "to think/miss", effect: SpellEffect::Heal(4) },
    Recipe { inputs: &["田", "心"], output_hanzi: "思", output_pinyin: "sī", output_meaning: "to ponder", effect: SpellEffect::Heal(3) },
    Recipe { inputs: &["女", "马"], output_hanzi: "妈", output_pinyin: "mā", output_meaning: "mother", effect: SpellEffect::Heal(3) },
    // Shield / Defense combos
    Recipe { inputs: &["山", "石"], output_hanzi: "岩", output_pinyin: "yán", output_meaning: "rock/cliff", effect: SpellEffect::Shield },
    Recipe { inputs: &["小", "土"], output_hanzi: "尘", output_pinyin: "chén", output_meaning: "dust", effect: SpellEffect::Shield },
    Recipe { inputs: &["石", "马"], output_hanzi: "码", output_pinyin: "mǎ", output_meaning: "number/code", effect: SpellEffect::Shield },
    Recipe { inputs: &["王", "田", "土"], output_hanzi: "理", output_pinyin: "lǐ", output_meaning: "logic/reason", effect: SpellEffect::Shield },
    Recipe { inputs: &["竹", "马"], output_hanzi: "笃", output_pinyin: "dǔ", output_meaning: "sincere/earnest", effect: SpellEffect::Shield },
    Recipe { inputs: &["竹", "木", "目"], output_hanzi: "箱", output_pinyin: "xiāng", output_meaning: "box/chest", effect: SpellEffect::Shield },
    // Strong hit / Strike combos
    Recipe { inputs: &["田", "力"], output_hanzi: "男", output_pinyin: "nán", output_meaning: "male/man", effect: SpellEffect::StrongHit(4) },
    Recipe { inputs: &["力", "口"], output_hanzi: "加", output_pinyin: "jiā", output_meaning: "to add/increase", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["手", "目"], output_hanzi: "看", output_pinyin: "kàn", output_meaning: "to look/watch", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["女", "口"], output_hanzi: "如", output_pinyin: "rú", output_meaning: "as if/like", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["口", "贝"], output_hanzi: "呗", output_pinyin: "bài", output_meaning: "to chant", effect: SpellEffect::StrongHit(3) },
    Recipe { inputs: &["口", "马"], output_hanzi: "吗", output_pinyin: "ma", output_meaning: "question particle", effect: SpellEffect::StrongHit(2) },
];

/// Try to forge a character from a set of radicals. Order-independent.
pub fn try_forge(radicals: &[&str]) -> Option<&'static Recipe> {
    for recipe in RECIPES {
        if recipe.inputs.len() == radicals.len() {
            // Check if all inputs are present (order-independent)
            let mut matched = vec![false; recipe.inputs.len()];
            let mut all_found = true;
            for rad in radicals {
                let mut found = false;
                for (i, inp) in recipe.inputs.iter().enumerate() {
                    if !matched[i] && inp == rad {
                        matched[i] = true;
                        found = true;
                        break;
                    }
                }
                if !found {
                    all_found = false;
                    break;
                }
            }
            if all_found && matched.iter().all(|m| *m) {
                return Some(recipe);
            }
        }
    }
    None
}

/// Get a subset of radicals available for a given floor.
/// Earlier floors have fewer radicals.
pub fn radicals_for_floor(floor: i32) -> &'static [Radical] {
    let count = match floor {
        1 => 10,
        2 => 15,
        3 => 20,
        4 => 25,
        _ => RADICALS.len(),
    };
    &RADICALS[..count.min(RADICALS.len())]
}
